# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'parqueadero_ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


    	pod 'Alamofire', '~> 4.5'
	pod 'AlamofireObjectMapper', '~> 5.0'
	pod 'PKHUD', '~> 5.0' 
	


  target 'parqueadero_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'parqueadero_iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

